### ISSUE TITLE
A few make issues

### ISSUE THREAD

**Issue by bunchmj** [defenseunicorns/tadpole#18]
**Describe the bug**
Readme has 'make cleanup', but Makefile has 'clean' target. Makefile target 'clean-unsafe' errors when running.

**To Reproduce**
1. ➜  tadpole git:(main) make cleanup
make: *** No rule to make target `cleanup'.  Stop.
2. ➜  tadpole git:(main) make clean-unsafe
make docker-clean
make[1]: *** No rule to make target `docker-clean'.  Stop.
make: *** [clean-unsafe] Error 2

**Expected behavior**
make should find the targets and do the things

**Comment by gphorvath** [comment]
Awesome, thank you for the PR @bunchmj
