### ISSUE TITLE
make docker-compose fails with default settings

### ISSUE THREAD

**Issue by remy415** [defenseunicorns/tadpole#4]
The 'make docker-compose' step of the installation fails due to missing submodule backend-whisper. Removing 'backend-whisper' section of the docker-compose file allows the command to work. I believe the issue is simply either the 'backend-whisper' reference was added but the submodule wasn't, or the submodule was previously present and removed in this version.

Alternatively, I'm assuming backend-whisper could be manually downloaded to the ./backend folder.

I am running this from a MacBook Pro M2 Max and MacOS Ventura 13.3. The installation seems to otherwise work as advertised.

**Comment by gphorvath** [comment]
This should also be addressed #6 you are welcome to test that branch out to see if this works better!
