### ISSUE TITLE
Makefile VERSION var results in fatal error message

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/tadpole#7]
Low criticality and really doesn't block anything. Likely a result of no tags established yet.

Noticing in the Makefile:
```
VERSION := $(shell git describe --abbrev=0 --tags)
```
when run this results in the following at the top of every execution:

```
fatal: No names found, cannot describe anything.
```

**Comment by gphorvath** [comment]
This isn't used currently. This will be removed in #8 until it is needed.
