### ISSUE TITLE
Request - Make clean option

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/tadpole#8]
Given the workflow in the Makefile - I would be interested if a `Make clean` command would be valuable in the development workflow/experience? 

Thinking about something with the context to quickly revert the state of the repository to that of something that could be updated without potentially including files that were modified during other Make commands - IE `docker-compose-build`

**Comment by gphorvath** [comment]
Would something like this work for what you are thinking @brandtkeller?

```bash
docker-clean:
	docker image rm -f tadpole-frontend
	docker image rm -f tadpole-backend
	docker image rm -f tadpole-backend-transcribe
	docker image rm -f tadpole-api
```

**Comment by brandtkeller** [comment]
That would be great!
